<?php
/**
 * This view is used to generate enumeration definition class files
 *
 * @var array $constants
 * @var string $namespace
 * @var string $className
 */
echo "<?php\n";
?>
/**
 * This file has been automatically generated by yii2-enum, do not change it manually.
 * @date <?php date('Y-m-d H:i:s'); ?>
 */

namespace <?php echo $namespace; ?>;

use opus\enum\AbstractEnum;

/**
 * Enumeration category PrevalenceThreshold.
 *
 * @package <?php echo $namespace; ?>
 */
class <?php echo $className; ?> extends AbstractEnum
{
<?php foreach ($constants as $key => $value) { ?>
    const <?php echo $key; ?> = <?php echo $value; ?>;
<?php } ?>
}
